# modify these multipliers to change the desirability.
weather_conditions_multiplier = {
    'Clear' : 1, 
    'Cloudy' : 0.9,
    'Fog' : 0.9,
    'Haze' :0.9,
    'Light Rain' : 0.6,
    'Mostly Cloudy' : 0.7,
    'Overcast' : 0.8,
    'Partly Cloudy' : 0.9,
    'Rain' : 0.2,
    'Rain Showers' : 0.2, 
    'Showers' : 0.2,
    'Thunderstorm' : 0.1,
    'Chance of Showers' : 0.5, 
    'Chance of Snow' : 0.5, 
    'Chance of Storm' : 0.5, 
    'Mostly Sunny' : 0.9,
    'Partly Sunny' : 1,
    'Scattered Showers' : 0.3, 
    'Sunny' : 1,
}
